routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', '\App\Blog\Front\Controllers\FrontController@getIndex')->name('front');
Route::get('/all-posts', '\App\Blog\Front\Controllers\FrontController@all')->name('posts.all');
Route::get('/post/{id}', '\App\Blog\Front\Controllers\FrontController@showPost')->name('posts.show');
Route::get('/contact', '\App\Blog\Front\Controllers\FrontController@contact')->name('contact');
Route::get('/about', '\App\Blog\Front\Controllers\FrontController@about')->name('about');
Route::resource('comments', 'CommentsController');
Route::resource('contacts', 'ContactController');






Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('login/github', [LoginController::class, 'redirectToProvider']);
Route::get('login/github/callback', [LoginController::class, 'handleProviderCallback']);

Route::group(['middleware' => 'auth'], function () {
    require base_path('app/Blog/Users/Routes/web.php');
    require base_path('app/Blog/Categories/Routes/web.php');
    require base_path('app/Blog/Posts/Routes/web.php');
    require base_path('app/Blog/Posts/Routes/web.php');
    require base_path('app/Blog/Tags/Routes/web.php');
    require base_path('app/Blog/Profile/Routes/web.php');
    require base_path('app/Blog/Testimonials/Routes/web.php');


});

app/Http/Controllers/Comments/Comment.php
<?php

namespace App\Http\Controllers\Comments;

use App\Blog\Posts\Post;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['user_id', 'post_id' ,'commentByName', 'commentByEmail', 'body'];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }


}

app/Http/Controllers/Comments/Requests/CreateCommentsRequest.php
<?php

namespace App\Http\Controllers\Comments\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateCommentsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'body'=>'required',
        ];
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Comments\Comment;
use App\Http\Controllers\Comments\Requests\CreateCommentsRequest;

class CommentsController extends Controller
{

    public function store(CreateCommentsRequest $request)
    {
        $inputs = $request->all();
        if(auth()->user()){
            $inputs['commentByName'] = auth()->user()->name;
            $inputs['commentByEmail'] = auth()->user()->email;
            $inputs['user_id'] = auth()->user()->id;
        }

        Comment::create($inputs);

        return back();
    }


}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Contacts\Contact;
use App\Http\Controllers\Contacts\Requests\CreateContactsRequest;

class ContactController extends Controller
{
    public $model;
    public $module;

    public function __construct(Contact $model)
    {
        $this->module = 'contact';
        $this->title = trans('app.contact');
        $this->model = $model;
    }
    public function index()
    {
        $data['module'] = $this->module;
        $data['page_title'] = trans('tags.List contact');
        $data['rows'] = $this->model->latest()->paginate();
        return view('admin.'.$this->module . '.index', $data);
    }

    public function store(CreateContactsRequest $request)
    {
        $inputs = $request->all();

        Contact::create($inputs);

        return back();
    }


}

app/Http/Controllers/Contacts/Contact.php
<?php

namespace App\Http\Controllers\Contacts;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = ['name', 'email' ,'subject', 'body'];



}

app/Http/Controllers/Contacts/Requests/CreateContactsRequest.php
<?php

namespace App\Http\Controllers\Contacts\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateContactsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'body'=>'required',
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('admin.layouts.master');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">
        {{ @$page_title }}
    </h6>
@endsection
@section('content')
    <div class="section-wrapper">
        <div class="form-layout form-layout-4">
        {!! Form::model($row,['method' => 'post','files' => true ] ) !!}
        {{ csrf_field() }}
        @include('admin.'.$module.'.form',$row)
        <!-- custom-file -->
            <div class="form-layout-footer mg-t-30">
                <button class="btn btn-primary bd-0">{{ trans('app.Save') }}</button>
            </div>
        {!! Form::close() !!}
        <!-- form-layout-footer -->
        </div>
        <!-- form-layout -->
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">
        {{ @$page_title }}
    </h6>
@endsection
@section('content')
    <div class="section-wrapper">
        <div class="form-layout form-layout-4">
        {!! Form::model($row,['method' => 'post','files' => true] ) !!} {{ csrf_field() }} {{method_field('put')}}
        @include('admin.'.$module.'.form',$row)
        <!-- custom-file -->
            <div class="form-layout-footer mg-t-30">
                <button class="btn btn-primary bd-0">{{ trans('app.Save') }}</button>
            </div>
        {!! Form::close() !!}
        <!-- form-layout-footer -->
        </div>
        <!-- form-layout -->
    </div>
@endsection

resources/views/admin/categories/form.blade.php
@php
    $attributes=['class'=>'form-control','label'=>trans('categories.title'),'placeholder'=>trans('categories.title')];
@endphp

@include('form.input',['name'=>'title','type'=>'text','attributes'=>$attributes])

    <div class="form-group">
            @include('form.input',[
            'name'=>'description',
            'value'=>$row->description,
            'type'=>'textarea',
            'attributes'=>[
                'class'=>'form-control',
                'id'=>'summary-ckeditor',
                'label'=>trans('categories.description'),
                'placeholder'=>trans('categories.description'),
                ]
            ])

    </div>

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">

        {{trans('app.List Categories')}}

    </h6>
@endsection
@section('content')
    <a href="categories/create" class="btn btn-success">
        <i class="fa fa-plus"></i> {{trans('app.Create')}}
    </a>
    <section class="section-wrapper">

        <div class="container bg-white">

        @if(count($rows))
            <div class="table-responsive">
                <table class="table display responsive nowrap">
                    <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Description</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($rows as $row)
                        <tr class="text-center">
                            <td>{{$row->id}}</td>
                            <td>{{$row->title}}</td>
                            <td>{!! $row->description !!}</td>
                            <td class="center">

                                @if(request('deleted') != 'yes')
                                    <a class="btn btn-success btn-xs" href="{{$module}}/edit/{{$row->id}}" title="{{trans('categories.Edit')}}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                        <form  class="d-inline" method="POST" action="{{route('categories.delete' , $row->id)}}">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button  type="submit" class="btn btn-danger btn-xs" value="Delete celebrities"
                                                     data-confirm="{{trans('categories.Are you sure you want to delete this item')}}?">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                @endif
                            </td>

                        </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            {{ $rows->links() }}
        @else
            <br>
                <p class="text-center text-bold"> {{trans("users.There is no results")}}</p>

        @endif
        </div>
    </section>

@endsection

resources/views/admin/contact/index.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">

        {{trans('app.List contacts')}}

    </h6>
@endsection
@section('content')
    <section class="section-wrapper">

        <div class="container bg-white">

        @if(count($rows))
            <div class="table-responsive">
                <table class="table display responsive nowrap">
                    <thead>
                    <tr>
                        <th class="text-center">Name</th>
                        <th class="text-center">email</th>
                        <th class="text-center">subject</th>
                        <th class="text-center">message</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($rows as $row)
                        <tr class="text-center">
                            <td>{{$row->name}}</td>
                            <td>{{$row->email}}</td>
                            <td>{{$row->subject}}</td>
                            <td>{{$row->body}}</td>

                        </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            {{ $rows->links() }}
        @else
            <br>
                <p class="text-center text-bold"> {{trans("users.There is no results")}}</p>

        @endif
        </div>
    </section>

@endsection

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>

    @include('admin.sections.css')

</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">

    <!-- Navbar -->
    @include('admin.sections.right_header')

    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
@include('admin.sections.navigation')


<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
    @include('flash::message')

    <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">{{ @$page_title }}</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ trans('app.Home') }}</a></li>
                            <li class="breadcrumb-item active">Dashboard v2</li>
                        </ol>
                    </div><!-- /.col -->
{{--                    @if(isset($breadcrumb))--}}
{{--                        @include('admin.sections.breadcrumb')--}}
{{--                    @endif--}}
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        @yield('content')
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    @include('admin.sections.footer')

</div>
<!-- ./wrapper -->

@include('admin.sections.js')

<script>
    $('div.alert').not('.alert-important').delay(4000).fadeOut(350);
</script>

</body>
</html>

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">
        {{ @$page_title }}
    </h6>
@endsection
@section('content')
    <div class="section-wrapper">
        <div class="form-layout form-layout-4">
        {!! Form::model($row,['method' => 'post','files' => true ] ) !!}
        {{ csrf_field() }}
        @include('admin.'.$module.'.form',$row)
        <!-- custom-file -->
            <div class="form-layout-footer mg-t-30">
                <button class="btn btn-primary bd-0">{{ trans('app.Save') }}</button>
            </div>
        {!! Form::close() !!}
        <!-- form-layout-footer -->
        </div>
        <!-- form-layout -->
    </div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">
        {{ @$page_title }}
    </h6>
@endsection
@section('content')
    <div class="section-wrapper">
        <div class="form-layout form-layout-4">
        {!! Form::model($row,['method' => 'post','files' => true] ) !!} {{ csrf_field() }} {{method_field('put')}}
        @include('admin.'.$module.'.form',$row)
        <!-- custom-file -->
            <div class="form-layout-footer mg-t-30">
                <button class="btn btn-primary bd-0">{{ trans('app.Save') }}</button>
            </div>
        {!! Form::close() !!}
        <!-- form-layout-footer -->
        </div>
        <!-- form-layout -->
    </div>
@endsection

resources/views/admin/tags/form.blade.php
@php
    $attributes=['class'=>'form-control','label'=>trans('tags.title'),'placeholder'=>trans('tags.title')];
@endphp

@include('form.input',['name'=>'title','type'=>'text','attributes'=>$attributes])

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">

        {{trans('app.List Tags')}}

    </h6>
@endsection
@section('content')
    <a href="tags/create" class="btn btn-success">
        <i class="fa fa-plus"></i> {{trans('app.Create')}}
    </a>
    <section class="section-wrapper">

        <div class="container bg-white">

        @if(count($rows))
            <div class="table-responsive">
                <table class="table display responsive nowrap">
                    <thead>
                    <tr>
                        <th class="text-center">Name</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($rows as $row)
                        <tr class="text-center">
                            <td>{{$row->title}} <span class="badge badge-primary ml-2">{{$row->posts->count()}}</span></td>
                            <td class="center">

                                @if(request('deleted') != 'yes')
                                    <a class="btn btn-success btn-xs" href="{{$module}}/edit/{{$row->id}}" title="{{trans('tags.Edit')}}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                        <form  class="d-inline" method="POST" action="{{route('tags.delete' , $row->id)}}">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button  type="submit" class="btn btn-danger btn-xs" value="Delete celebrities"
                                                     data-confirm="{{trans('tags.Are you sure you want to delete this item')}}?">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                @endif
                            </td>

                        </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            {{ $rows->links() }}
        @else
            <br>
                <p class="text-center text-bold"> {{trans("users.There is no results")}}</p>

        @endif
        </div>
    </section>

@endsection

resources/views/admin/testimonials/create.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">
        {{ trans('app.Create Testimonials') }}
    </h6>
@endsection
@inject('model','App\Blog\Testimonials\Testimonial')
@section('content')

    <div class="section-wrapper">
        <div class="form-layout form-layout-4">
            {!! Form::model($model,[
                'action' => '\App\Blog\Testimonials\Controllers\TestimonialsController@store',
                'enctype' => 'multipart/form-data'
            ]) !!}
{{--            @include('partials.validation_errors')--}}
            @include('admin.testimonials.form')

            {!! Form::close() !!}
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace('summary-ckeditor');
    </script>
@endsection

resources/views/admin/testimonials/edit.blade.php
@extends('admin.layouts.master')
@section('title')
    <h6 class="slim-pagetitle">
        {{ trans('app.Edit Testimonials') }}
    </h6>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="section-wrapper">
            <div class="form-layout form-layout-4">
                {!! Form::model($row,[
                    'action' => ['\App\Blog\Testimonials\Controllers\TestimonialsController@update',$row->id],
                    'method' => 'put',
                    'enctype' => 'multipart/form-data'
                ]) !!}
{{--                @include('partials.validation_errors')--}}
                @include('admin.testimonials.form')
                {!! Form::close() !!}

            </div>
        </div>


    </section>
    <!-- /.content -->
@endsection


@section('scripts')
    <script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace('summary-ckeditor');
    </script>
@endsection

resources/views/admin/testimonials/form.blade.php
<div class="form-group">
    @include('form.input',[
    'name'=>'title',
    'value'=>$row->Title,
    'type'=>'text',
    'attributes'=>[
        'class'=>'form-control dateTimePicker',
        'label'=>trans('testimonial.title'),
        'placeholder'=>trans('testimonial.title'),
        ]
    ])
</div>
<div class="form-group">
    @include('form.input',[
    'name'=>'description',
    'value'=>$row->description,
    'type'=>'textarea',
    'attributes'=>[
        'class'=>'form-control dateTimePicker',
        'id'=>'summary-ckeditor',
        'label'=>trans('testimonial.description'),
        'placeholder'=>trans('testimonial.description'),
        ]
    ])

</div>

<div class="form-group">
    @include('form.file',[
     'name'=>'testimonialimg',
     'value'=> $row->testimonialimg,
     'class' => 'form-control',
     'attributes'=>[
     'label'=>trans('testimonial.Picture'),
     'required'  => ($row->id ? false : true),
     ]])
</div>

<div class="form-group">
    <button class="btn btn-primary" type="submit">save</button>
</div>



{{--@section('styles')--}}
    {{--@parent--}}
    {{--{{ Html::style(mix('assets/admin/css/users/edit.css')) }}--}}
{{--@endsection--}}

{{--@section('scripts')--}}
    {{--@parent--}}
    {{--{{ Html::script(mix('assets/admin/js/users/edit.js')) }}--}}
{{--@endsection--}}

resources/views/front/contact.blade.php
@extends('front.layouts.master')
@section('head')
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('images/liv1.jpeg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-3 bread">Contact us</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{{route('front')}}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Contact us <i class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('content')
<section class="ftco-section contact-section">
    <div class="container">
        <div class="row d-flex mb-5 contact-info">
            <div class="col-md-12 mb-4">
                <h2 class="h3">Contact Information</h2>
            </div>
            <div class="w-100"></div>
            <div class="col-md-4">
                <p><strong>Address :</strong> 198 West 21th Street, Suite 721 New York NY 10016</p>
            </div>
            <div class="col-md-4">
                <p><strong>Phone :</strong> <a href="tel://01211440047">01211440047</a></p>
            </div>
            <div class="col-md-4">
                <p><strong>Email :</strong> <a href="mailto:info@yoursite.com">tawakl.at@gmail.com</a></p>
            </div>

        </div>
        <div class="row block-9 no-gutters">
            <div class="col-lg-6 order-md-last d-flex">
                <form method="post" action="{{ route('contacts.store') }}" class="bg-light p-4 p-md-5 contact-form">
                    @csrf
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Your Name" name="name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Your Email" name="email">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Subject" name="subject">
                    </div>
                    <div class="form-group">
                        <textarea name="body" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                    </div>
                </form>

            </div>

            <div class="col-lg-6 d-flex">
                <img src="/images/ynwa.jpg" width="590" height="558">
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/front/posts/show.blade.php
@extends('front.layouts.master')
@section('head')
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({{asset('storage/'. $post->postimg)}});" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-3 bread">{{$post->title??''}}</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{{route('front')}}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="blog.html">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('content')

<div class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <p class="mb-5">
                    <img src="{{asset('storage/'. $post->postimg)}}" alt="" class="img-fluid">
                </p>
                <p> {!! $post->description!!}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        @foreach($post->tags as $tag)
                        <a href="#" class="tag-cloud-link">{{$tag->title}}</a>
                        @endforeach
                    </div>

                </div>

                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="{{asset('storage/'. $post->author->image)}}" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>{{ $post->author->name}}</h3>
                        <p>{{ $post->author->about}}</p>
                    </div>
                </div>

                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{$post->comments->count()}} Comments</h3>
                    @foreach($post->comments as $comment)
                    <ul class="comment-list">
                        <li class="comment">
                            <div class="comment-body">
                                <h3>{{ $comment->commentByName }}</h3>
                                <div class="meta mb-3">{{$comment->created_at}}</div>
                                <p class="w-25">{{$comment->body}}</p>
{{--                                <p><a href="#" class="reply">Reply</a></p>--}}
                            </div>
                        </li>
                        @endforeach

                    </ul>
                    <!-- END comment-list -->

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form class="p-5 bg-light" method="post" action="{{ route('comments.store') }}">
                            @csrf
                        @if(!auth()->user())

                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" id="name" name="commentByName">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" id="email" name="commentByEmail">
                            </div>
                            @endif
                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="body" id="message" cols="30" rows="7" class="form-control"></textarea>
                                <input type="hidden" name="post_id" value="{{ $post->id }}"/>

                            </div>
                            <div class="form-group">
                                <input type="submit" value="Add Comment" class="btn py-3 px-4 btn-primary">
                            </div>

                        </form>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">

                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>
                        @foreach($categories as $category)
                        <li><a href="#">{{$category->title}} <span class="ion-ios-arrow-forward"></span></a></li>
                        @endforeach
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>

                    @foreach($posts as $post)

                    <div class="block-21 mb-4 d-flex">
                        <img src="{{asset('storage/'. $post->postimg)}}" class="blog-img mr-4">

                        <div class="text">

                            <h3 class="heading"><a href="#">{{$post->title}}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span>{{$post->created_at}}</a></div>
                                <div><a href="#"><span class="icon-person"></span> {{ $post->author->name}}</a></div>
                                <div><a href="#"><span class="icon-chat"></span> {{ $post->comments->count()}}</a></div>
                            </div>
                        </div>
                    </div>
                    @endforeach

                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        @foreach($tags as $tag)
                            <a href="#">{{$tag->title}} <span class="tag-cloud-link"></span></a>
                        @endforeach
                    </div>
                </div>

            </div>

        </div>
    </div>
</div> <!-- .section -->

@endsection